#! /bin/sh

VERSION=4.2
DISTDIR=/u/pyg/files

# small safety tests
if [ ! -f module/pgmodule.c ]
then
	echo "Hmmm.  Are you sure you are in the right directory?"
	exit 1
fi
if [ ! -d $DISTDIR ]
then
	echo "Hmmm.  Are you sure you are on the right server?"
	exit 1
fi

if [ -f BETA ]
then
	VERSION=$VERSION-pre`date +"%y%m%d"`
	PACKAGE=pygresql.pkg-beta
	SYMLINK=PyGreSQL-beta.tgz
else
	PACKAGE=pygresql.pkg
	SYMLINK=PyGreSQL.tgz
fi

# Package up as a source tarball in the distribution directory.
# Note that this does essentially the same as "python setup.py sdist",
# except this also makes the docs and bundles them as source and html.

TD=PyGreSQL-$VERSION
TF=$DISTDIR/$TD.tgz

MODFILES="pg.py pgdb.py pgmodule.c
          pgfs.h pgtypes.h
          setup.py setup.cfg"
DOCFILES="docs/Makefile docs/make.bat docs/*.rst
          docs/contents docs/download docs/community
          docs/_static docs/_templates"
HTMLFILES="docs/_build/html"
TESTFILES="tests/*.py"

echo "Making source tarball..."

./mkdocs

rm -rf $TD
mkdir $TD
mkdir -p $TD/docs/_build/html
mkdir $TD/tests
cp $MODFILES $TD
cp -r $DOCFILES $TD/docs
cp -r $HTMLFILES $TD/docs/_build
cp $TESTFILES $TD/tests
tar -cvzf $TF $TD
chmod 644 $TF
rm -rf $TD
rm -f $DISTDIR/$SYMLINK
ln -s $TD.tgz $DISTDIR/$SYMLINK

echo "$TF has been built"
