#! /bin/sh

VERSION=4.2
DISTDIR=/u/pyg/files

# small safety tests
if [ ! -f pgmodule.c ]
then
	echo "Hmmm.  Are you sure you are in the right directory?"
	exit 1
fi
if [ ! -d $DISTDIR ]
then
	echo "Hmmm.  Are you sure you are on the right server?"
	exit 1
fi

if [ -f BETA ]
then
	VERSION=$VERSION-pre`date +"%y%m%d"`
	PACKAGE=pygresql.pkg-beta
	SYMLINK=PyGreSQL-beta.tgz
else
	PACKAGE=pygresql.pkg
	SYMLINK=PyGreSQL.tgz
fi

# Package up as a source tarball in the distribution directory.

echo "Making source tarball..."

# Make sure that the documentation has been built.

./mkdocs

# Package as source distribution.

rm -rf build dist

python setup.py sdist

DF=`ls dist`
TF=$DISTDIR/$DF

cp dist/$DF $TF
chmod 644 $TF

rm -f $DISTDIR/$SYMLINK
ln -s $DF $DISTDIR/$SYMLINK

echo "$TF has been built."
